### ISSUE TITLE
LockPlugin not recognizing RangePlugin

### ISSUE THREAD

**Issue by hacktisch** [easepick/easepick#219]
When trying to use the LockPlugin with my RangePlugin I get this warning in my console:
`LockPlugin: options minDays, maxDays, selectForward, selectBackward required RangePlugin.`
Yet I have the RangePlugin included, and it's working despite the LockPlugin not doing anything. But now I cannot limit the amount of days. Below is an example Svelte component and you can see it in action in the StackBlitz link below that.

```
<script>
    import { onMount, onDestroy } from "svelte";
    import { easepick } from '@easepick/core';
    import {RangePlugin} from '@easepick/range-plugin';
    import {LockPlugin} from '@easepick/lock-plugin';
  
    let picker;
    let ref;

    onMount(() => {
        picker = new easepick.create({
            element: ref,
            css: ["/datepicker.css"],
            inline: true,
            plugins: [RangePlugin, LockPlugin],
            LockPlugin: {
                maxDays: 3
            }
        });
    });
    onDestroy(() => {
        if(picker){
            picker.destroy();
        }
    });
</script>

<input type="hidden" bind:this={ref} />

```
[View on StackBlitz](https://stackblitz.com/edit/vitejs-vite-knbjze?file=src%2FApp.svelte) and check the console warning.

**Comment by chris78er** [comment]
Same here. To suppress the warning, I deleted the following code in node_modules/@easepick/bundle/dist/index.esm.js:

console.warn(`${this.getName()}: options ${t.join(", ")} required RangePlugin.`)

Not a clean solution, but sufficient for the moment until a bugfix arrives.

**Comment by hacktisch** [comment]
> Same here. To suppress the warning, I deleted the following code in node_modules/@easepick/bundle/dist/index.esm.js:
> 
> console.warn(`${this.getName()}: options ${t.join(", ")} required RangePlugin.`)
> 
> Not a clean solution, but sufficient for the moment until a bugfix arrives.

I had then also tried the same and removed the check entirely from the code, hoping that the lock plugin would work with the range selection but it did not. Did you manage to get it to work?

**Comment by chris78er** [comment]
Try to replace

`import { easepick } from '@easepick/core';`
`import {RangePlugin} from '@easepick/range-plugin';`
`import {LockPlugin} from '@easepick/lock-plugin';`

with

`import { easepick, LockPlugin, RangePlugin } from '@easepick/bundle';`

and delete

`console.warn(${this.getName()}: options ${t.join(", ")} required RangePlugin.)`

in **node_modules/@easepick/bundle/dist/index.esm.js**

**Comment by chris78er** [comment]
Your configuration with the LockPlugin works in a regular html file but non in Svelte. No idea why...

**Comment by hacktisch** [comment]
Thanks Chris,
Indeed it doesn't work (does not work also when I import from the bundle)
The console warning isn't my concern, the Lock plugin simply doesn't get activated. I just made a workaround for now in my Svelte. For whoever this may be of help, here it is:

```
const maxDays = 5;

picker = new easepick.create({
    element: ref,
    plugins: [RangePlugin],
    // other options
    setup(picker) {
        picker.on("select", (e) => {
            try {
                let { start, end } = e.detail;
                // Calculate the difference in days between start and end
                const diffInDays = Math.round(
                    (end - start) / (1000 * 60 * 60 * 24)
                );
                // If the difference exceeds 'maxDays', adjust the end date
                if (diffInDays >= maxDays) {
                    end = new Date(start);
                    end.setDate(end.getDate() + (maxDays - 1));
                    picker.setEndDate(end);
                }
            } catch (e) {}
        });
    },
});
```

**Comment by anthony0030** [comment]
I also get the error ```LockPlugin: options minDays, maxDays, selectForward, selectBackward required RangePlugin.``` but everything works as expected.

**Comment by p3drosola** [comment]
I fixed it like this: 

```js
import * as easepick from '@easepick/bundle';

window.easepick = easepick; // fixes issues loading plugins

// initialization
 plugins: [ 'RangePlugin', 'LockPlugin'],
```

**Comment by t-lock** [comment]
> I fixed it like this:
> 
> import * as easepick from '@easepick/bundle';
> 
> window.easepick = easepick; // fixes issues loading plugins
> 
> // initialization
>  plugins: [ 'RangePlugin', 'LockPlugin'],

I am still experiencing this issue (LockPlugin does not work with RangePlugin) in Easepick 1.2.1 (and I am also using Svelte).

Was hoping this would be a quick fix, but does not appear to have any effect.

The configuration I am doing is very basic (doesn't use range-only options):

```
      plugins: ['RangePlugin', 'LockPlugin'],
      LockPlugin: {
        minDate: new Date(),
      },
```
